version: "3.8"

services:
    frontend:
        build:
            context: ./front
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - ./front:/project
        command: npm run start

    backend:
        build:
            context: ./server
            dockerfile: Dockerfile
        env_file:
            - ./server/.env
        restart: always
        ports:
            - "3200:80"
        volumes:
            - ./server:/var/www/html

    database:
        image: mariadb:10.8.2
        restart: always
#        ports:
#            - "127.0.0.1:3500:3306"
        environment:
            MYSQL_DATABASE: tp-data
            MYSQL_ROOT_PASSWORD: 4t8MrD5hDRChnq
        volumes:
            - database:/var/lib/mysql
#             Pour lancer un dump automatiquement au montage du conteneur
#            - ./database/dump.sql:/docker-entrypoint-initdb.d/dump.sql

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - '8080:80'
        environment:
            - PMA_ARBITRARY=1

volumes:
    database:
